### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by jaygray0919** [joseignm/GraFa#14]
appears to be offline: http://grafa.dcc.uchile.cl/

**Comment by joseignm** [comment]
it's up again, thanks for the tip

**Comment by jaygray0919** [comment]
hey. still seeing:
`404 Not Found
nginx/1.10.3`

**Comment by aidhog** [comment]
Hmm, it seems another student of mine is using the machine for some experiments; once she's done I'll restart the service (and maybe try find a better way to load balance). Pardon the dust.

edit: should be today or tomorrow

**Comment by aidhog** [comment]
Sorry for the long delay! Hopefully the downtimes have now been resolved.

**Comment by jaygray0919** [comment]
good; thanks; will experiment
