### ISSUE TITLE
GraFa on web is not working!

### ISSUE THREAD

**Issue by oratosa** [joseignm/GraFa#15]
Could you please check the server condition? 
http://grafa.dcc.uchile.cl/

**Comment by aidhog** [comment]
Server is fine so it seems to be a networking issue.
Should hopefully be resolved within 8 hours.
Thanks for reporting!

**Comment by oratosa** [comment]
OK, I will check it out later.
Thanks!

**Comment by aidhog** [comment]
It's back up now.
